user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    client_header_timeout 60;
    client_body_timeout   60;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 4096;

    gzip off;
    gzip_comp_level 4;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;


    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    include /etc/nginx/conf.d/*.conf;


    # HTTP -> HTTPS redirect
    server {
        listen 80;
        listen [::]:80;

        server_name dldm.kr;

        # Let's Encrypt challenge
        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
        }

        return 301 https://$host$request_uri;
    }


    # HTTPS server
    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name dldm.kr;

        root /usr/share/nginx/html;

        ssl_certificate /etc/letsencrypt/live/dldm.kr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dldm.kr/privkey.pem;

        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 10m;

        ssl_ciphers PROFILE=SYSTEM;
        ssl_prefer_server_ciphers on;


        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
        }

        include conf.d/elasticbeanstalk/*.conf;
    }
}